import os

class GlobalConstants:
    duplicateFilesFolder = os.path.join("duplicateFilesFolder", "") #The quotes at the end add an OS-specific folder slash
    #uniqueLinesFilename = "uniqueLines.txt"
    previouslySelectedFolderForDuplicatesCheck = "previouslySelectedFolder.txt" #store the folder name of the folder that was last selected, so that the User does not have to re-navigate from the beginning
    #dummyPrefix = "dummy_" #This is used in the Test class below, but needed to be initialized here since other constants in the Test class need to use it. #because gitignore is primed to ignore files and folders starting with this prefix. Helps avoid committing the dummy files generated by test cases
    EVENT_CANCEL = 'Cancel'
    EVENT_EXIT = 'Cancel'
    YES_BUTTON = 'Yes'
    NO_BUTTON = 'No'
    #alreadyProcessedFile = "."
    #supportedImageFormats = ['jpg', 'jpeg', 'png', 'webp'] #let all extensions mentioned here be in lower case. More can be added after testing.
    FIRST_POSITION_IN_LIST = 0
    VCF_EXTENSION = '.vcf'
    #UNDO_FILE_EXTENSION = ".undo"
    #TEXT_FILE_MIME_TYPE = "text/"

# class FileSearchModes:
#     choice_None = 'Exit'
#     choice_fileBinary = 'Duplicate file segregation'
#     choice_imagePixels = 'Duplicate image segregation'    
#     choice_lineDuplicates = 'Unique lines finder'
#     choice_residualFileDeletion = 'Delete files (like Thumbs.db etc.)'
#     choice_undoFileMove = 'Undo files that were moved and renamed'
    
# class FilenameMatching:
#     fullString = "fullString"
#     wildcard = "wildcard"

# class Tests:    
#     testFolder = os.path.join("tests", GlobalConstants.dummyPrefix + "folders", "") #The quotes at the end add an OS-specific folder slash