import os

class GlobalConstants:
    duplicateFilesFolder = os.path.join("duplicateFilesFolder", "") #The quotes at the end add an OS-specific folder slash
    #uniqueLinesFilename = "uniqueLines.txt"
    previouslySelectedFolderForDuplicatesCheck = "previouslySelectedFolder.txt" #store the folder name of the folder that was last selected, so that the User does not have to re-navigate from the beginning
    #dummyPrefix = "dummy_" #This is used in the Test class below, but needed to be initialized here since other constants in the Test class need to use it. #because gitignore is primed to ignore files and folders starting with this prefix. Helps avoid committing the dummy files generated by test cases
    EVENT_CANCEL = 'Cancel'
    EVENT_EXIT = 'Cancel'
    YES_BUTTON = 'Yes'
    NO_BUTTON = 'No'
    #alreadyProcessedFile = "."
    #supportedImageFormats = ['jpg', 'jpeg', 'png', 'webp'] #let all extensions mentioned here be in lower case. More can be added after testing.
    FIRST_POSITION_IN_LIST = 0
    VCF_EXTENSION = '.vcf'
    NUMBER_OF_TEL_END_DIGITS = 8 #number of digits at the end of the telephone number to consider for matching with phone numbers of other contacts
    COLON_DELIMITER = ":"
    SEMICOLON_DELIMITER = ";"
    #UNDO_FILE_EXTENSION = ".undo"
    #TEXT_FILE_MIME_TYPE = "text/"

class Properties:#property names present in a VCard https://en.wikipedia.org/wiki/VCard#toc-Properties
    BEGIN = 'BEGIN'
    VCARD = 'VCARD'
    EMAIL = 'EMAIL'
    END = 'END'
    FN = 'FN' #formatted name 
    N = 'N' #name
    NAME = 'NAME'
    TEL = 'TEL'
    